# Generated by Django 2.2 on 2019-04-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20190314_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(default='Как новая, без следов использования', max_length=120),
        ),
    ]
